// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nSFBwCwtEONNGq_H-HjvZ-QgXT51UzM',
    appId: '1:265470045772:web:210f14c8d9b872d6978ee9',
    messagingSenderId: '265470045772',
    projectId: 'taller3-25b12',
    authDomain: 'taller3-25b12.firebaseapp.com',
    storageBucket: 'taller3-25b12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMQfXrWOhxzLfQQRSeB1TZX3N8I3QuQU',
    appId: '1:265470045772:android:7a057d6aced96f1e978ee9',
    messagingSenderId: '265470045772',
    projectId: 'taller3-25b12',
    storageBucket: 'taller3-25b12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nSFBwCwtEONNGq_H-HjvZ-QgXT51UzM',
    appId: '1:265470045772:ios:210f14c8d9b872d6978ee9',
    messagingSenderId: '265470045772',
    projectId: 'taller3-25b12',
    authDomain: 'taller3-25b12.firebaseapp.com',
    storageBucket: 'taller3-25b12.firebasestorage.app',
    iosBundleId: 'com.example.firabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nSFBwCwtEONNGq_H-HjvZ-QgXT51UzM',
    appId: '1:265470045772:ios:210f14c8d9b872d6978ee9',
    messagingSenderId: '265470045772',
    projectId: 'taller3-25b12',
    authDomain: 'taller3-25b12.firebaseapp.com',
    storageBucket: 'taller3-25b12.firebasestorage.app',
    iosBundleId: 'com.example.firabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0nSFBwCwtEONNGq_H-HjvZ-QgXT51UzM',
    appId: '1:265470045772:web:210f14c8d9b872d6978ee9',
    messagingSenderId: '265470045772',
    projectId: 'taller3-25b12',
    authDomain: 'taller3-25b12.firebaseapp.com',
    storageBucket: 'taller3-25b12.firebasestorage.app',
  );
}